### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by clarklight** [ksloan/jquery-mobile-swipe-list#2]
Hi 

  I am just wondering if i can alter the sensitivity for the swipe. Because when i scroll up and down, the swipe moves from left to right at the same time. 

Wondering if i can alter that by the Math part? 
    change = Math.min(Math.max(-100, change), 100) // restrict to -100px left, 0px right
            e.currentTarget.style.left = change + 'px'
            if (change < -10) disable_scroll() // disable scroll once we hit 10px horizontal slide
        })

**Comment by ksloan** [comment]
https://github.com/ksloan/jquery-mobile-swipe-list/blob/master/index.html#L200
http://api.jquery.com/animate/
